os: linux
dist: bionic
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - "14.15.1"
jobs:
  include:
    - stage: test
      script: npm run test

    - stage: npm release
      branches:
        only:
          - master
      script:
        - echo "Deploying to npm ..."
        - npm run report-coverage
      deploy:
        provider: script
        script: npm semantic-release
