os: linux
dist: bionic
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 15
jobs:
  include:
  - stage: test
    script: npm run test
  - stage: coverage
    script: 
     - npm run report-coverage
     - npm run semantic-release
# branches:
#   only:
#     - master